// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9u7qtHTAH_oYas-LlR0XVIyKbjH9rXg8',
    appId: '1:284695538243:web:2aa74b0f0460dc2f0c82f6',
    messagingSenderId: '284695538243',
    projectId: 'thrift-3dc44',
    authDomain: 'thrift-3dc44.firebaseapp.com',
    storageBucket: 'thrift-3dc44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfJa7YeMs58-YMiqqhRWX8nZJlcO22tAA',
    appId: '1:284695538243:android:ac2800030ff8747c0c82f6',
    messagingSenderId: '284695538243',
    projectId: 'thrift-3dc44',
    storageBucket: 'thrift-3dc44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSPYtxUUQmQX2qZ7nKZ_5euVsDOqFd-tI',
    appId: '1:284695538243:ios:f29ea069e49698600c82f6',
    messagingSenderId: '284695538243',
    projectId: 'thrift-3dc44',
    storageBucket: 'thrift-3dc44.appspot.com',
    androidClientId: '284695538243-1eeg4jgad56jhsmentkc4ahvugkbhdt4.apps.googleusercontent.com',
    iosClientId: '284695538243-pfjl25mhcvi5hf84tuf3q22i4qogmskd.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirft',
  );
}
